default: &default
  adapter: postgresql
  timeout: 5000
  statement_limit: 100
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: birthday_app_dev

test:
  <<: *default
  database: birthday_app_test

production:
  <<: *default
  database: birthday_app_prod
